version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go Backend API (Producer)
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes: # <-- ADD THIS
      - doc-converter-data:/app/tmp/downloads

  # Go Worker (Consumer)
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    deploy:
      replicas: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes: # <-- AND THIS
      - doc-converter-data:/app/tmp/downloads

  # Caddy Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - backend

# Declare the shared volume at the top level
volumes: # <-- AND THIS WHOLE BLOCK
  doc-converter-data: